// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Mohawk Medicine",
  domain: "mohawkmedicine.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "2655 Eglinton Ave E, Toronto, ON M1K 2S2",
  streetAddress: "2655 Eglinton Ave E",
  postalCode: "M1K 2S2",
  phone: "(437) 577-1809",
  phoneIntl: "+14375771809",
  neighborhood: "Eglinton East / Scarborough / Kennedy",
  nearbyAreas: ["Eglinton East", "Kennedy Road", "Scarborough", "Golden Mile", "Birchmount", "Warden", "Kennedy Station area", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com",
  mapEmbedUrl: "https://maps.google.com/maps?q=Mohawk%20Medicine%202655%20Eglinton%20Ave%20E%2C%20Toronto%2C%20ON%20M1K%202S2&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.7330",
  longitude: "-79.2500",
  hours: ["Open 24 Hours"],
  seoTitle: "Mohawk Medicine | Weed Dispensary in Toronto",
  metaDescription: "Mohawk Medicine is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Eglinton East", "Kennedy Road", "Scarborough"],
  introVariant: "Welcome to Mohawk Medicine, your premier weed dispensary in Toronto situated right on 2655 Eglinton Ave E. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near Eglinton East / Scarborough / Kennedy or a weed shop near Kennedy Road, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant Eglinton East / Scarborough / Kennedy district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Ample free parking is available in the retail plaza lot",
  transitNote: "Conveniently located near Kennedy Subway Station and served by TTC routes.",
  sectionTitle: "Serving Customers Near Eglinton East and Scarborough"
};
