import { STORE_NAP } from "./nap";

export const gbpLocation = {
  storeName: STORE_NAP.brandName,
  legalName: STORE_NAP.legalName,
  domain: STORE_NAP.domain,
  city: STORE_NAP.city,
  province: STORE_NAP.addressRegion,
  country: STORE_NAP.addressCountry,
  slug: "weed-dispensary-toronto",
  address: STORE_NAP.address,
  streetAddress: STORE_NAP.streetAddress,
  postalCode: STORE_NAP.postalCode,
  phone: STORE_NAP.phoneDisplay,
  phoneIntl: STORE_NAP.phoneIntl,
  neighborhood: "Eglinton East / Scarborough / Kennedy",
  nearbyAreas: ["Eglinton East", "Kennedy Road", "Scarborough", "Golden Mile", "Birchmount", "Warden", "Kennedy Station area", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: STORE_NAP.hasMap,
  mapEmbedUrl: STORE_NAP.mapEmbedUrl,
  latitude: String(STORE_NAP.latitude),
  longitude: String(STORE_NAP.longitude),
  hours: [STORE_NAP.hours],
  seoTitle: "Mohawk Medicine | Weed Dispensary in Toronto",
  metaDescription: "Mohawk Medicine is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Eglinton East", "Kennedy Road", "Scarborough"],
  introVariant: "Mohawk Medicine is a weed dispensary in Toronto situated at 2655 Eglinton Ave E. Adults 19+ can use this page to check store basics, menu categories, and current public listings before visiting the Scarborough area shop.",
  neighborhoodDescription: "Located in the vibrant Eglinton East / Scarborough / Kennedy district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Ample free parking is available in the retail plaza lot",
  transitNote: "Check current local transit or map details before visiting.",
  sectionTitle: "Serving Customers Near Eglinton East and Scarborough"
};
