import { STORE_NAP } from "./nap";

export const gbpLocation = {
  storeName: STORE_NAP.brandName,
  legalName: STORE_NAP.legalName,
  domain: STORE_NAP.domain,
  city: STORE_NAP.city,
  province: STORE_NAP.addressRegion,
  country: STORE_NAP.addressCountry,
  slug: "weed-dispensary-toronto",
  address: STORE_NAP.address,
  streetAddress: STORE_NAP.streetAddress,
  postalCode: STORE_NAP.postalCode,
  phone: STORE_NAP.phoneDisplay,
  phoneIntl: STORE_NAP.phoneIntl,
  neighborhood: "Eglinton East / Scarborough / Brimley",
  nearbyAreas: ["Eglinton East", "Brimley Rd", "Scarborough"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: STORE_NAP.hasMap,
  mapEmbedUrl: STORE_NAP.mapEmbedUrl,
  latitude: String(STORE_NAP.latitude),
  longitude: String(STORE_NAP.longitude),
  hours: [STORE_NAP.hours],
  seoTitle: "Mohawk Medicine | Weed Dispensary Scarborough | Eglinton East",
  metaDescription: "Mohawk Medicine is a 24-hour weed dispensary in Scarborough on Eglinton Ave E, with flower tiers, pre-rolls, edibles, vapes, concentrates, and walk-in details for adults 19+.",
  localLandmarks: ["Eglinton East", "Brimley Rd"],
  introVariant: "Mohawk Medicine is a weed dispensary in Scarborough at 2655 Eglinton Ave E. Adults 19+ can use this page to check store basics, menu categories, and current public listings before visiting the Eglinton East shop.",
  neighborhoodDescription: "The shop is on Eglinton Avenue East in Scarborough, near Brimley Rd, with local retail around the plaza and mapable walk-in access at 2655 Eglinton Ave E.",
  parkingNote: "Ample free parking is available in the retail plaza lot",
  transitNote: "Check current local transit or map details before visiting.",
  sectionTitle: "Serving Customers on Eglinton East near Brimley"
};
